### ISSUE TITLE
prevent hierarchical collections for recursive paths

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-pcdm#46] opened 2015-05-06 20:10 UTC
Add validation to prevent...
```
coll1.collections = [coll2]
coll2.collections = [coll3]
coll3.collections = [coll1]   # don't allow because already part of the collection path
```

**Comment by awead** [comment] 2015-05-07 12:19
Related to #23

**Comment by awead** [comment] 2015-05-07 14:36
duplicate of #50

**Closed** 2015-05-08 14:19 UTC
Labels: in progress
